Feature/auth screen
PhilippMolitor/haw-ms-sweng-s21 pull request #8
Opened 2021-06-19 18:03 UTC by josiela

Implemented basic logic for auth-screen
Started adding CSS but realized that I'm not good at CSS so I but that at the back of the queue.

2021-06-20 16:22 UTC, PhilippMolitor requested changes

2021-06-20 16:22 UTC, PhilippMolitor commented on src/components/PinInput.tsx
> +    if (Number(pin) < 1000 || Number(pin) > 9999) {
wir sollten alle pins erlauben, 0993 sollte eig. gueltig sein, oder gibt es gegengruende?

2021-06-20 16:22 UTC, PhilippMolitor commented on src/pages/AuthPage.tsx
> +    authenticate(pin);
hier kommt ein bool zurueck, ob die auth erfolgreich war. das muss dann wieder zurueck zum pininput transportiert werden.

2021-06-21 09:10 UTC, josiela commented on src/pages/AuthPage.tsx
> +    authenticate(pin);
Ja, das ergibt total Sinn! Ich merke nur, ich picke überhaupt nicht, wie das funktioniert 😅

2021-06-21 09:11 UTC, josiela commented on src/components/PinInput.tsx
> +    if (Number(pin) < 1000 || Number(pin) > 9999) {
Nee hast recht :) Hab ich angepasst

2021-06-21 17:31 UTC, merged